import { existsSync } from 'node:fs'
import { socialCardName } from '@stacksjs/image'

const siteOut = './dist/site'
const docsOut = './dist/docs/.bunpress'
const socialSrc = './public/social'

// Dedicated per-feature pages: the extension build names each output by its
// template basename, so dist/<slug>.html → /features/<slug>/.
const FEATURE_SLUGS = ['network-blocking', 'youtube-twitch', 'popups', 'controls']

async function main(): Promise<void> {
  await ensureExists('./dist/marketing.html', 'dist/marketing.html is missing. Run bun run build first.')
  await ensureExists('./dist/features.html', 'dist/features.html is missing. Run bun run build first.')
  await ensureExists('./dist/privacy.html', 'dist/privacy.html is missing. Run bun run build first.')
  for (const slug of FEATURE_SLUGS)
    await ensureExists(`./dist/${slug}.html`, `dist/${slug}.html is missing. Run bun run build first.`)
  await ensureExists(docsOut, 'Bunpress output is missing. Run bun run docs:build first.')

  await Bun.$`rm -rf ${siteOut}`
  await Bun.$`mkdir -p ${siteOut}/icons ${siteOut}/docs ${siteOut}/features ${siteOut}/screenshots`

  // Home page is served at the site root, where the extension build's
  // page-relative asset refs (styles.css, marketing.js) already resolve.
  await Bun.write(`${siteOut}/index.html`, await Bun.file('./dist/marketing.html').text())

  // Features hub + each dedicated feature page live one or two directories deep,
  // so their assets are re-rooted to absolute and the shared script is injected.
  await Bun.write(`${siteOut}/features/index.html`, siteize(await Bun.file('./dist/features.html').text()))

  // Privacy policy at /privacy/ (shareable clean URL, linked from the footer).
  await Bun.$`mkdir -p ${siteOut}/privacy`
  await Bun.write(`${siteOut}/privacy/index.html`, siteize(await Bun.file('./dist/privacy.html').text()))

  for (const slug of FEATURE_SLUGS) {
    await Bun.$`mkdir -p ${siteOut}/features/${slug}`
    await Bun.write(`${siteOut}/features/${slug}/index.html`, siteize(await Bun.file(`./dist/${slug}.html`).text()))
  }

  await Bun.write(`${siteOut}/styles.css`, await Bun.file('./dist/styles.css').arrayBuffer())
  await Bun.write(`${siteOut}/marketing.js`, await Bun.file('./dist/marketing.js').arrayBuffer())
  await Bun.$`cp -R ./dist/icons/. ${siteOut}/icons/`
  // Product screenshots used by the marketing + feature pages (also live under /docs).
  await Bun.$`cp ./docs/public/screenshots/popup.png ./docs/public/screenshots/dashboard.png ${siteOut}/screenshots/`
  await Bun.$`cp -R ${docsOut}/. ${siteOut}/docs/`

  // Social cards, generated by `bun run og` and committed. Generating them
  // needs a headless browser to capture the popup, which the deploy runner is
  // not guaranteed to have — so the cards are build inputs here, not outputs,
  // and a browserless deploy ships the committed set rather than failing.
  await ensureExists(socialSrc, 'public/social is missing. Run `bun run og` first, and commit the result.')
  await Bun.$`mkdir -p ${siteOut}/social`
  await Bun.$`cp -R ${socialSrc}/. ${siteOut}/social/`

  await verifySocialCards()

  console.log(`Built Very Good AdBlock site into ${siteOut}`)
}

/**
 * Every card a page declares has to exist.
 *
 * A stale `og:image` is the failure this whole pipeline exists to prevent, and
 * it is invisible: the page renders, the build passes, and the link preview is
 * a broken image until somebody shares one and notices. Renaming a page in
 * `config/images.ts` without updating its template should stop the build, not
 * ship.
 */
async function verifySocialCards(): Promise<void> {
  const pages = await Array.fromAsync(new Bun.Glob('**/*.html').scan({ cwd: siteOut, absolute: true }))
  const missing = new Set<string>()
  const declared = new Set<string>()

  for (const page of pages) {
    const html = await Bun.file(page).text()
    for (const [, file] of html.matchAll(/https:\/\/verygoodadblock\.org\/social\/([\w.-]+)/g)) {
      declared.add(file)
      if (!existsSync(`${siteOut}/social/${file}`))
        missing.add(`${file} (declared by ${page.slice(siteOut.length + 1)})`)
    }
  }

  if (missing.size) {
    throw new Error(
      `Social cards declared in the templates were never generated:\n  ${[...missing].join('\n  ')}\n`
      + `Run \`bun run og\`, or add the page to \`social.pages\` in config/images.ts.`,
    )
  }

  // The other direction: a card configured but never referenced is a page that
  // still ships whatever `og:image` it had before, which is the failure this
  // pipeline exists to prevent and the one nobody notices.
  const images = (await import('../../config/images')).default
  const orphans = (images.social?.pages ?? [])
    .map(page => `${socialCardName(page.path)}.jpg`)
    .filter(file => !declared.has(file))

  if (orphans.length) {
    throw new Error(
      `Social cards are configured but no page declares them:\n  ${orphans.join('\n  ')}\n`
      + `Add the og:image tags to the page's template, or drop it from \`social.pages\`.`,
    )
  }
}

/**
 * Re-root a sub-page's assets to absolute paths and inject the shared marketing
 * script. The extension build emits page-relative asset refs (styles.css,
 * icons/...) and strips inline/companion scripts under its CSP sanitizer; both
 * resolve fine for the root marketing page but not for pages served from
 * /features/ or /features/<slug>/.
 */
function siteize(html: string): string {
  const out = html
    .replace(/(href|src)="styles\.css"/g, '$1="/styles.css"')
    .replace(/(href|src)="icons\//g, '$1="/icons/')
  if (out.includes('/marketing.js'))
    return out
  return out.replace('</body>', '  <script type="module" src="/marketing.js"></script>\n</body>')
}

async function ensureExists(path: string, message: string): Promise<void> {
  if (!existsSync(path)) throw new Error(message)
}

await main()
