/**
 * Capture the REAL extension popup (rendered against the seeded dashboard
 * fixture) as static HTML into `resources/partials/popup-preview.html`. The marketing
 * extension build inlines it into the hero, so the landing page shows
 * the actual popup component in code — styled by the shared styles.css, crisp at
 * any resolution, no screenshot. Regenerate after popup UI changes:
 *   bun run preview:marketing
 */
import { existsSync } from 'node:fs'
import { mkdir } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { dashboardState, injectShim, shimScript } from './lib/preview-fixture'

const dist = resolve('dist')
const outPath = resolve('resources/partials/popup-preview.html')

if (!existsSync(join(dist, 'popup.html')))
  throw new Error('dist/popup.html is missing. Run `bun run build` first.')

await mkdir(resolve('resources/partials'), { recursive: true })

const shim = shimScript(dashboardState())

const server = Bun.serve({
  port: 0,
  async fetch(request) {
    const url = new URL(request.url)
    if (url.pathname === '/popup.html')
      return new Response(injectShim(await Bun.file(join(dist, 'popup.html')).text(), shim), { headers: { 'content-type': 'text/html; charset=utf-8' } })
    const asset = join(dist, url.pathname.replace(/^\//, ''))
    if (existsSync(asset))
      return new Response(Bun.file(asset))
    return new Response('Not found', { status: 404 })
  },
})

const view = new Bun.WebView({
  width: 390,
  height: 820,
  backend: { type: 'chrome', url: false, argv: ['--proxy-server=direct://', '--proxy-bypass-list=*', '--force-device-scale-factor=1', '--hide-scrollbars'] },
})

try {
  await view.navigate(`http://127.0.0.1:${server.port}/popup.html`)
  const start = Date.now()
  while (Date.now() - start < 4000) {
    const ready = await view.evaluate<boolean>(`Boolean(document.querySelector('.popup-frame[data-view="ready"]'))`).catch(() => false)
    if (ready)
      break
    await Bun.sleep(120)
  }
  await Bun.sleep(400)
  // Capture the filled popup markup (chart bars, stats, favicon, top sources all
  // resolved). It carries the shipping ids/classes; on the marketing page they're
  // inert and styled by the shared stylesheet.
  const frame = await view.evaluate<string>(`document.querySelector('.popup-frame').outerHTML`)
  const markup = `<!-- Generated by resources/scripts/generate-marketing-preview.ts from the real popup. Do not edit by hand; run \`bun run preview:marketing\`. -->\n${frame}\n`
  await Bun.write(outPath, markup)
  console.log(`Wrote ${outPath} (${markup.length} bytes)`)
}
finally {
  view.close()
  server.stop(true)
  Bun.WebView.closeAll()
}
