import type { ExtensionConfig } from '@stacksjs/browser-extension'
import { defineExtension } from '@stacksjs/browser-extension'

/**
 * Very Good AdBlock — MV3 extension config.
 *
 * This fully replaces the old hand-written manifest and build script
 * boilerplate: `@stacksjs/browser-extension` derives the Chrome/Firefox
 * manifests, bundles content/background + page scripts, builds & sanitizes the
 * stx pages, compiles the DNR ruleset, copies assets, and packages the
 * store-ready zips from this single declaration (`buddy extension:build` /
 * `extension:package`). The one app-specific step — inlining the popup preview
 * into the marketing hero — stays as a `postBuild` hook.
 */
// Explicitly typed so the default export is inferrable under
// `isolatedDeclarations` (the test suite imports this config directly).
const extension: ExtensionConfig = defineExtension({
  name: 'Very Good AdBlock',
  description: 'Removes ads, pop-ups, and YouTube and Twitch interruptions at the source. Fast, private, no telemetry.',
  geckoId: 'extension@verygoodadblock.org',
  chromeWebStore: {
    publisherId: process.env.CHROME_WEB_STORE_PUBLISHER_ID ?? '',
    itemId: 'ondclgjpkclbchfbbjdikdpdnopbachc',
  },
  firefoxAddons: {
    channel: 'listed',
    // AMO is the only store of the three whose API takes listing screenshots
    // on the way past — Apple's takes them with the version's metadata, and
    // Chrome's has no endpoint for them at all. Left undeclared, the listing
    // kept two images someone uploaded by hand at mismatched sizes, captioned
    // "A screenshot showcasing the extension".
    //
    // Generated by `bun run screenshots` and committed, because the release
    // workflow never runs a capture.
    screenshots: [
      'resources/web-store/01.png',
      'resources/web-store/02.png',
      'resources/web-store/03.png',
    ],
    screenshotCaptions: [
      'Ads, pop-ups and trackers blocked at the source, before the page can show them.',
      'Pause any site in one click, with protection resuming on its own.',
      'Lifetime totals, 60 days of history and per-site stats — all of it local.',
    ],
  },
  safariBundleId: 'org.verygoodadblock.VeryGoodAdBlock',
  safariTeamId: '3JJRNQW6B7',
  safariPlatforms: ['macos', 'ios'],
  safariAppCategory: 'public.app-category.utilities',
  safariAppStore: {
    locale: 'en-US',
    subtitle: 'Fast, private ad blocking',
    privacyPolicyUrl: 'https://verygoodadblock.org/privacy/',
    description: `Very Good AdBlock blocks ads, trackers, cookie banners, and intrusive pop-ups in Safari on iPhone, iPad, and Mac. It uses Safari's content-blocking and web-extension APIs to stop requests before they load, helps reduce page clutter and data use, and gives you simple per-site controls.

Privacy first: no telemetry, no browsing-history collection, no selling or sharing of data. Settings and blocking statistics remain on your devices. Optional browser-account sync is handled by your browser vendor, not our servers.

Features:
• Network-level ad and tracker blocking
• YouTube and Twitch ad defenses
• Pop-up and pop-under protection
• Per-site pause, allowlist, and blocklist controls
• Optional cookie-banner hiding
• Local blocking and savings statistics

Install the app, then enable Very Good AdBlock in Settings > Apps > Safari > Extensions on iPhone or iPad, or Safari > Settings > Extensions on Mac.`,
    // App Review wants to know what changed in an update, and without this the
    // version localization carries whatever the previous submission said.
    // Written for the people reading the listing, so it covers what they can
    // see or feel — not the build pipeline behind it.
    whatsNew: `• Links that pass through a redirector — sign-in flows, newsletter and search result links — now open normally instead of being caught by the pop-up guard.
• The dashboard's 60-day history chart fills its panel, so the bars are readable at a glance.
• Consistent typography across the popup and dashboard on every device.`,
    keywords: 'ad blocker,privacy,tracker blocker,popups,Safari,YouTube,Twitch,cookie banners',
    supportUrl: 'https://github.com/chrisbbreuer/very-good-adblock/issues',
    marketingUrl: 'https://verygoodadblock.org',
    copyright: '2026 Chris Breuer',
    primaryCategory: 'UTILITIES',
    contentRightsDeclaration: 'USES_THIRD_PARTY_CONTENT',
    price: '0',
    baseTerritory: 'USA',
    releaseType: 'AFTER_APPROVAL',
    availableInNewTerritories: true,
    usesIdfa: false,
    usesNonExemptEncryption: false,
    reviewContact: {
      firstName: 'Chris',
      lastName: 'Breuer',
      phone: '+1 808-218-8241',
      email: 'chrisbreuer93@gmail.com',
      notes: 'No account or login is required. Launch the app once, then enable Very Good AdBlock in Settings > Apps > Safari > Extensions on iPhone or iPad, or Safari > Settings > Extensions on Mac. The extension processes blocking locally and sends no browsing data to us.',
    },
    // Generated by `buddy generate:app-store` from `config/images.ts`. The
    // names are the generator's (`<display-type>-<nn>.png`), numbered per
    // device class in slide order.
    //
    // Committed rather than built on the way to the upload:
    // `extension:safari:publish` does try to regenerate them first, but the
    // composition needs the captures in `dist/captures/`, and the release
    // workflow never runs a capture — so on CI it warns ("using the committed
    // screenshots — could not regenerate") and uploads these. Keeping them
    // current is `bun run screenshots`, run and committed by a human.
    //
    // The dashboard slide is absent from iPhone on purpose: it is a wide
    // surface, and on a 1290x2796 frame the slack reads as empty background.
    screenshots: {
      APP_DESKTOP: [
        'resources/app-store/screenshots/app-desktop-01.png',
        'resources/app-store/screenshots/app-desktop-02.png',
        'resources/app-store/screenshots/app-desktop-03.png',
      ],
      APP_IPHONE_67: [
        'resources/app-store/screenshots/app-iphone-67-01.png',
        'resources/app-store/screenshots/app-iphone-67-02.png',
      ],
      APP_IPAD_PRO_3GEN_129: [
        'resources/app-store/screenshots/app-ipad-pro-3gen-129-01.png',
        'resources/app-store/screenshots/app-ipad-pro-3gen-129-02.png',
        'resources/app-store/screenshots/app-ipad-pro-3gen-129-03.png',
      ],
    },
    submitForReview: true,
  },
  // Site-only pages built into dist for the marketing site — never shipped in
  // the appex (extension:safari:app keeps them out of the synced Resources).
  safariExclude: [
    'marketing.html',
    'marketing.js',
    'features.html',
    'network-blocking.html',
    'youtube-twitch.html',
    'popups.html',
    'controls.html',
    'privacy.html',
  ],
  targets: ['chrome', 'firefox', 'safari'],

  background: 'src/background/index.ts',

  content: [
    { entry: 'src/content/index.ts', out: 'content.js', matches: ['http://*/*', 'https://*/*'], runAt: 'document_start' },
    { entry: 'src/content/x-inpage.ts', matches: ['*://x.com/*', '*://*.x.com/*', '*://twitter.com/*', '*://*.twitter.com/*'], runAt: 'document_start', world: 'MAIN' },
    { entry: 'src/content/yt-inpage.ts', matches: ['*://*.youtube.com/*'], runAt: 'document_start', world: 'MAIN' },
    { entry: 'src/content/popup-guard.ts', matches: ['http://*/*', 'https://*/*'], runAt: 'document_start', world: 'MAIN', allFrames: true, matchAboutBlank: true },
  ],

  pages: {
    popup: { template: 'resources/views/popup.stx', script: 'src/ui/popup.ts' },
    options: { template: 'resources/views/options.stx', script: 'src/ui/options.ts' },
    // The marketing site pages are bundled alongside (reused by the site build).
    // Only `marketing` carries the shared script bundle (theme toggle + subscribe
    // form); the site build injects `/marketing.js` into the other pages.
    extra: {
      // Shown in place of the browser's ERR_BLOCKED_BY_CLIENT error when a
      // top-level navigation is blocked (src/background/index.ts). Not
      // web-accessible: only the background navigates a tab to it.
      blocked: { template: 'resources/views/blocked.stx', script: 'src/ui/blocked.ts' },
      marketing: { template: 'resources/views/marketing.stx', script: 'resources/scripts/marketing.ts' },
      features: 'resources/views/features.stx',
      privacy: 'resources/views/privacy.stx',
      'feature-network-blocking': 'resources/views/features/network-blocking.stx',
      'feature-youtube-twitch': 'resources/views/features/youtube-twitch.stx',
      'feature-popups': 'resources/views/features/popups.stx',
      'feature-controls': 'resources/views/features/controls.stx',
    },
  },

  icons: {
    16: 'icons/icon-16.png',
    32: 'icons/icon-32.png',
    48: 'icons/icon-48.png',
    128: 'icons/icon-128.png',
  },
  actionIcons: {
    16: 'icons/toolbar-16.png',
    32: 'icons/toolbar-32.png',
  },

  public: 'public',
  assets: { 'styles.css': 'resources/css/styles.css' },

  // One logical ruleset, emitted across several files: addons.mozilla.org will
  // not parse a file over 5 MB, and the full pretty-printed ruleset is well
  // past that. Browsers evaluate all enabled rulesets together, so the split is
  // invisible at runtime. Keep in sync with `rulesPerRuleset`.
  rules: [
    { id: 'very_good_adblock_static_rules', path: 'rules/static.json', source: 'src/rules/ruleset-1.ts' },
    { id: 'very_good_adblock_static_rules_2', path: 'rules/static-2.json', source: 'src/rules/ruleset-2.ts' },
    { id: 'very_good_adblock_static_rules_3', path: 'rules/static-3.json', source: 'src/rules/ruleset-3.ts' },
  ],

  manifest: {
    // No `tabs`: the `chrome.tabs` API itself never needed it, and the sensitive
    // fields we do read (`url`, `pendingUrl`, `favIconUrl`) are already granted by
    // the http/https host permissions below. Every read is http(s)-gated, so the
    // permission bought nothing but a scarier install warning.
    permissions: ['declarativeNetRequest', 'declarativeNetRequestFeedback', 'webRequest', 'storage', 'alarms'],
    hostPermissions: ['http://*/*', 'https://*/*'],
    minimumChromeVersion: '111',
    firefoxMinVersion: '142.0',
    webAccessibleResources: [
      { resources: ['stubs/googletag.js', 'stubs/adsbygoogle.js'], matches: ['<all_urls>'] },
    ],
  },

  hooks: {
    // Inline the real popup component into the marketing hero, replacing the
    // #popup-preview placeholder. Runs after sanitize so the markup survives.
    async postBuild({ outdir }) {
      const file = `${outdir}/marketing.html`
      if (!(await Bun.file(file).exists()))
        return
      let html = await Bun.file(file).text()

      // Inline the real popup component into the hero, replacing the
      // #popup-preview placeholder. Runs after sanitize so the markup survives.
      const partial = 'resources/partials/popup-preview.html'
      const placeholder = /<div class="hero-device" id="popup-preview"[^>]*><\/div>/
      if ((await Bun.file(partial).exists()) && placeholder.test(html)) {
        const frame = (await Bun.file(partial).text()).replace(/^<!--[\s\S]*?-->\s*/, '').trim()
        const label = 'The Very Good AdBlock popup: 47 ads blocked on this page, 8.4 GB of data saved, 20 hours of video time recovered, and a chart of the last 24 hours.'
        const replacement = `<div class="hero-device" role="img" aria-label="${label}"><div class="popup-preview popup-shell" aria-hidden="true">${frame}</div></div>`
        html = html.replace(placeholder, replacement)
      }

      await Bun.write(file, html)
    },
  },
})

export default extension
